# Generated by Django 5.0.2 on 2024-03-03 06:39

import charta_management.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='author_images/')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plot', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('series_number', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_image', models.ImageField(upload_to='')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, validators=[charta_management.validators.isbn_validator])),
                ('added_date', models.DateField(auto_now_add=True)),
                ('publisher', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
                ('languages', models.CharField(max_length=200, null=True)),
                ('plot', models.TextField(null=True)),
                ('book_file', models.FileField(upload_to='')),
                ('authors', models.ManyToManyField(to='charta_management.author')),
                ('genres', models.ManyToManyField(to='charta_management.genre')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charta_management.series')),
            ],
        ),
    ]
