# Generated by Django 5.0.2 on 2024-03-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charta_management', '0002_alter_genre_description_alter_series_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='authors',
            field=models.ManyToManyField(null=True, to='charta_management.author'),
        ),
    ]
