# Generated by Django 5.0.2 on 2024-03-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charta_management', '0003_series_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='authors',
            field=models.ManyToManyField(to='charta_management.author'),
        ),
    ]
