# Generated by Django 5.0.2 on 2024-03-07 13:32

import charta_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charta_management', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[charta_management.validators.isbn_validator]),
        ),
    ]
